steps:
- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      echo "***********************"
      echo "$BRANCH_NAME"
      echo "***********************"

- id: 'tf init'
  name: 'hashicorp/terraform:1.0.7'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
        for dir in environments/*/
        do
          cd ${dir}
          env=${dir%*/}
          env=${env#*/}
          echo ""
          echo "*************** TERRAFORM INIT ***************"
          echo "******** At environment: ${env} ********"
          echo "*************************************************"
          terraform init -upgrade || exit 1
          cd ../../
        done

# [START tf-plan]
- id: 'tf plan'
  name: 'hashicorp/terraform:1.0.7'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      
        for dir in environments/*/
        do
          cd ${dir}
          env=${dir%*/}
          env=${env#*/}
          echo ""
          echo "*************** TERRAFORM PLAN ***************"
          echo "******** At environment: ${env} ********"
          echo "*************************************************"
          terraform plan || exit 1
          cd ../../
        done
# [END tf-plan]
# [START tf-apply]
- id: 'tf apply'
  name: 'hashicorp/terraform:1.0.7'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
        for dir in environments/*/
        do
          cd ${dir}
          env=${dir%*/}
          env=${env#*/}
          echo ""
          echo "*************** TERRAFORM APPLY ***************"
          echo "******** At environment: ${env} ********"
          echo "*************************************************"

          terraform apply -auto-approve
        done

options:
  logging: 'CLOUD_LOGGING_ONLY'